import org.jetbrains.changelog.Changelog
import org.jetbrains.changelog.ChangelogSectionUrlBuilder
import org.jetbrains.changelog.ExtensionsKt
import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.jetbrains.intellij.platform.gradle.tasks.VerifyPluginTask

plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.16.0'
    id 'org.jetbrains.changelog' version '2.1.2'
}

group project.pluginGroup
version project.pluginVersion

def pluginVerifierOfflineProvider = providers.gradleProperty("pluginVerifierOffline")
        .map { it.toBoolean() }
        .orElse(true)

repositories {
    mavenLocal()
    maven { url "https://maven.aliyun.com/repository/public" }
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    compileOnly group: 'org.projectlombok', name: 'lombok', version: project.lombokVersion
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: project.lombokVersion

    intellijPlatform {
        create(project.platformType, project.platformVersion)
        bundledPlugin 'com.intellij.java'
        bundledPlugin 'org.intellij.plugins.markdown'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.javaVersion as Integer)
    }
    sourceCompatibility = JavaVersion.toVersion(project.javaVersion)
    targetCompatibility = JavaVersion.toVersion(project.javaVersion)
}

intellijPlatform {
    buildSearchableOptions = false
    projectName = project.pluginName

    pluginConfiguration {
        name = project.pluginName
        version = project.pluginVersion
        description = file(project.pluginDescription).getText('UTF-8')
        changeNotes = provider {
            changelog.renderItem(
                    changelog.getLatest(),
                    Changelog.OutputType.HTML
            )
        }

        ideaVersion {
            sinceBuild = project.pluginSinceBuild
            if (project.pluginUntilBuild?.trim()) {
                untilBuild = project.pluginUntilBuild
            } else {
                untilBuild = provider { null }
            }
        }
    }

    pluginVerification {
        failureLevel = [
                VerifyPluginTask.FailureLevel.COMPATIBILITY_PROBLEMS
        ]

        ides {
            project.pluginVerifierIdeVersions
                    .split(',')
                    .collect { it.trim() }
                    .findAll { !it.isEmpty() }
                    .each { create(IntelliJPlatformType.IntellijIdeaUltimate, it) }
        }
    }

    publishing {
        token = providers.gradleProperty("intellijPlatformPublishingToken")
        channels = providers.gradleProperty("pluginPublishChannels").map {
            it.split(',')
                    .collect { channel -> channel.trim() }
                    .findAll { channel -> !channel.isEmpty() }
        }
    }
}

changelog {
    path = file("CHANGELOG.md").canonicalPath
    header = "[${-> version.get()}] - ${ExtensionsKt.date("yyyy-MM-dd")}"
    keepUnreleasedSection = true
    unreleasedTerm = "[Unreleased]"
    groups = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
    lineSeparator = "\n"
    combinePreReleases = true
    sectionUrlBuilder = { repositoryUrl, currentVersion, previousVersion, isUnreleased -> "foo" } as ChangelogSectionUrlBuilder
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.named('test') {
    failOnNoDiscoveredTests = false
}

tasks.named('verifyPlugin', VerifyPluginTask) {
    offline.set(pluginVerifierOfflineProvider)
}

tasks.named('runIde') {
    jvmArgs project.runIdeJvmArgs.split(',').collect { it.trim() }.findAll { !it.isEmpty() }
}
